global proc AEMP2_Node_TriggerTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    editorTemplate -beginLayout "Max Payne 2 :: Trigger" -collapse 0;

        editorTemplate -beginLayout "Base" -collapse 0;
                editorTemplate -addControl "Hidden";
                editorTemplate -addControl "ExcludeFromGame";
                editorTemplate -addControl "ExcludeFromLighting";
                editorTemplate -addControl "EnableExportRegrouping";
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Trigger" -collapse 0;
                editorTemplate -addControl "Player";
                editorTemplate -addControl "Use";
                editorTemplate -addControl "Enemy";
                editorTemplate -addControl "Bullet";
                editorTemplate -addControl "LookAt";
                editorTemplate -addControl "Visibility";
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Animation" -collapse 0;
                editorTemplate -addControl "ActivatorsUseAnimation";
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

    editorTemplate -endLayout;

    editorTemplate -addSeparator;

    editorTemplate -addExtraControls;

    editorTemplate -endScrollLayout;
}