global proc AEMP2_Node_WayPointTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    editorTemplate -beginLayout "Max Payne 2 :: WayPoint" -collapse 0;

        editorTemplate -beginLayout "Base" -collapse 0;
                editorTemplate -addControl "Hidden";
                editorTemplate -addControl "ExcludeFromGame";
                editorTemplate -addControl "ExcludeFromLighting";
                editorTemplate -addControl "EnableExportRegrouping";
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

    editorTemplate -endLayout;

    editorTemplate -addSeparator;

    editorTemplate -addExtraControls;

    editorTemplate -endScrollLayout;
}