global proc AEMP2_Node_LevelItemTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    editorTemplate -beginLayout "Max Payne 2 :: Level Item" -collapse 0;

        editorTemplate -beginLayout "Base" -collapse 0;
                editorTemplate -addControl "Hidden";
                editorTemplate -addControl "ExcludeFromGame";
                editorTemplate -addControl "ExcludeFromLighting";
                editorTemplate -addControl "EnableExportRegrouping";
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Level Item" -collapse 0;
                editorTemplate -addControl "ItemName";
        editorTemplate -endLayout;

    editorTemplate -endLayout;

    editorTemplate -addSeparator;

    editorTemplate -addExtraControls;

    editorTemplate -endScrollLayout;
}