global proc AEMP2_Node_LevelItemTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    editorTemplate -beginLayout "Max Payne 2 :: Level Item" -collapse 0;

        editorTemplate -beginLayout "Base" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Hidden" -addControl "na_hidden";
                editorTemplate -label "Exclude From Game" -addControl "na_excludeFromGame";
                editorTemplate -label "Exclude From Lighting" -addControl "na_excludeFromLighting";
                editorTemplate -label "Enable Export Regrouping" -addControl "na_enableExportRegrouping";
                editorTemplate -addSeparator;
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Level Item" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Common Item" -addControl "na_itemNameCommon";
                editorTemplate -addSeparator;
                editorTemplate -label "Use Custom" -addControl "na_itemNameUseCustom";
                editorTemplate -label "Custom Item" -addControl "na_itemNameCustom";
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

    editorTemplate -endLayout;

    editorTemplate -addSeparator;

    editorTemplate -addExtraControls;

    editorTemplate -endScrollLayout;
}