global proc AEMP2_Node_AinTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    editorTemplate -beginLayout "Max Payne 2 :: AIN" -collapse 0;

        editorTemplate -beginLayout "Base" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Hidden" -addControl "na_hidden";
                editorTemplate -label "Exclude From Game" -addControl "na_excludeFromGame";
                editorTemplate -label "Exclude From Lighting" -addControl "na_excludeFromLighting";
                editorTemplate -label "Enable Export Regrouping" -addControl "na_enableExportRegrouping";
                editorTemplate -addSeparator;
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

    editorTemplate -endLayout;

    editorTemplate -addSeparator;

    editorTemplate -addExtraControls;

    editorTemplate -endScrollLayout;
}