global proc AEMP2_Node_EnemyTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    editorTemplate -beginLayout "Max Payne 2 :: Enemy" -collapse 0;

        editorTemplate -beginLayout "Base" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Hidden" -addControl "na_hidden";
                editorTemplate -label "Exclude From Game" -addControl "na_excludeFromGame";
                editorTemplate -label "Exclude From Lighting" -addControl "na_excludeFromLighting";
                editorTemplate -label "Enable Export Regrouping" -addControl "na_enableExportRegrouping";
                editorTemplate -addSeparator;
                editorTemplate -callCustom "AEMP2_Node_EnemyTemplate_create_fsm_edit_button" "AEMP2_Node_EnemyTemplate_update_fsm_edit_button" $nodeName;
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Group" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Enemy Group" -addControl "na_enemyGroup";
                editorTemplate -addSeparator;
                editorTemplate -callCustom "AEMP2_Node_EnemyTemplate_create_group_edit_button" "AEMP2_Node_EnemyTemplate_update_group_edit_button" $nodeName;
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Skin" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Common Skin" -addControl "na_skinCommon";
                editorTemplate -addSeparator;
                editorTemplate -label "Use Custom" -addControl "na_skinUseCustom";
                editorTemplate -label "Custom Skin" -addControl "na_skinCustom";
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

        editorTemplate -addSeparator;

        editorTemplate -beginLayout "Activator's Use Animation" -collapse 0;
            editorTemplate -beginNoOptimize;
                editorTemplate -label "Common Animation" -addControl "na_activatorsAnimationCommon";
                editorTemplate -addSeparator;
                editorTemplate -label "Use Custom" -addControl "na_activatorsAnimationUseCustom";
                editorTemplate -label "Custom Animation" -addControl "na_activatorsAnimationCustom";
            editorTemplate -endNoOptimize;
        editorTemplate -endLayout;

    editorTemplate -endLayout;

    editorTemplate -addSeparator;

    editorTemplate -addExtraControls;

    editorTemplate -endScrollLayout;
}

//FSM Edit button
global proc AEMP2_Node_EnemyTemplate_create_fsm_edit_button(string $nodeName)
{
    button -label "Edit FSM" -command ("python(\"from max_payne_maya.mp2nodes.mp2_fsm_ui import perform_edit_fsm_action; perform_edit_fsm_action(r'" + $nodeName + "')\")") mp2FsmEditorButton;
}

global proc AEMP2_Node_EnemyTemplate_update_fsm_edit_button(string $nodeName)
{
    button -e -command ("python(\"from max_payne_maya.mp2nodes.mp2_fsm_ui import perform_edit_fsm_action; perform_edit_fsm_action(r'" + $nodeName + "')\")") mp2FsmEditorButton;
}
//FSM Edit button

//FSM Edit button
global proc AEMP2_Node_EnemyTemplate_create_group_edit_button(string $nodeName)
{
    button -label "Edit FSM" -command ("python(\"from max_payne_maya.mp2nodes.mp2_fsm_ui import perform_edit_fsm_action; perform_edit_fsm_action(r'" + $nodeName + "')\")") mp2FsmEditorButton;
}

global proc AEMP2_Node_EnemyTemplate_update_group_edit_button(string $nodeName)
{
    button -e -command ("python(\"from max_payne_maya.mp2nodes.mp2_fsm_ui import perform_edit_fsm_action; perform_edit_fsm_action(r'" + $nodeName + "')\")") mp2FsmEditorButton;
}
//FSM Edit button